server:
  port: 8189
  servlet:
    context-path: /shop
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-other: false
jwt:
    secret: djaehtrq36tr8wtefegfgaefie
    lifetime: 36000000

